version: '3.4'

services:
  webapp:
    build: ./api/webapiproj
    ports:
      - "80:5115"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  frontend:
    build:
      context: ./frontend/productdata
    ports:
      - "4200:4200"
    command: sh -c "npm start"
